
package PackageArbolMVias;

public class FormularioMVias extends javax.swing.JFrame {
    ArbolMVias Al;
    ArbolMVias BB;
    public FormularioMVias() {
        initComponents();
        Al = new ArbolMVias();
        BB = new ArbolMVias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonInsertar = new javax.swing.JButton();
        txtEntrada = new javax.swing.JTextField();
        jButtonInOrden = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonmostrarPares = new javax.swing.JButton();
        jButtonPruebas = new javax.swing.JButton();
        jButtonExiste = new javax.swing.JButton();
        txtAuxiliar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        jButtoniIgualadadArbol = new javax.swing.JButton();
        jButtonSumaElementos = new javax.swing.JButton();
        parcial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonInsertar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonInsertar.setText("INSERTAR");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        txtEntrada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButtonInOrden.setText("InOrden");
        jButtonInOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInOrdenActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("ENTRADA DE DATOS");

        jLabel2.setText("ARBOL A");

        jButtonmostrarPares.setText("mostrarPares");
        jButtonmostrarPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmostrarParesActionPerformed(evt);
            }
        });

        jButtonPruebas.setText("Prueba de Metodos");
        jButtonPruebas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPruebasActionPerformed(evt);
            }
        });

        jButtonExiste.setText("ExisteX");
        jButtonExiste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExisteActionPerformed(evt);
            }
        });

        txtAuxiliar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAuxiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuxiliarActionPerformed(evt);
            }
        });

        jLabel3.setText("Auxiliar");

        txtSalida.setColumns(20);
        txtSalida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSalida.setRows(5);
        jScrollPane1.setViewportView(txtSalida);

        jButtoniIgualadadArbol.setText("Igualdad de Arbol");
        jButtoniIgualadadArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoniIgualadadArbolActionPerformed(evt);
            }
        });

        jButtonSumaElementos.setText("Suma Elementos");
        jButtonSumaElementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumaElementosActionPerformed(evt);
            }
        });

        parcial.setText("Parcial");
        parcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parcialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInsertar)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSumaElementos)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtoniIgualadadArbol)
                        .addGap(113, 113, 113)
                        .addComponent(parcial))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonInOrden)
                                .addGap(30, 30, 30)
                                .addComponent(txtAuxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(43, 43, 43)
                                .addComponent(jButtonExiste)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jButtonPruebas))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jButtonmostrarPares)))))
                .addGap(0, 419, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInsertar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonInOrden)
                            .addComponent(txtAuxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jButtonExiste)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPruebas)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonmostrarPares)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSumaElementos)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButtoniIgualadadArbol))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(parcial)))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
       // int x = Integer.parseInt(txtEntrada.getText());
       // Al.Insertar(x);
//        Al.Insertarzxd(30);
//        Al.Insertarzxd(40);
//        Al.Insertarzxd(50);
//        Al.Insertarzxd(20); 
//        Al.Insertarzxd(31); 
       
     
        Al.Insertar(15);
        Al.Insertar(21);
        Al.Insertar(10);
        Al.Insertar(13);
        Al.Insertar(15);
        Al.Insertar(17);
        Al.Insertar(21);
        Al.Insertar(25);
        Al.Insertar(12);
        
//        Al.Insertar(30);
//        Al.Insertar(40);
//        Al.Insertar(50);
//        Al.Insertar(80);
//        Al.Insertar(33);
//        Al.Insertar(35);
//        Al.Insertar(38);
//        Al.Insertar(20);
//        Al.Insertar(25);
//        Al.Insertar(27);
//        Al.Insertar(15);
//        Al.Insertar(34);

     
        BB.Insertar(30);
       BB.Insertar(40);
       BB.Insertar(50);
    /*    BB.Insertar(33);
        BB.Insertar(35);
        BB.Insertar(38);
        BB.Insertar(20);
        BB.Insertar(25);
        BB.Insertar(27);
        BB.Insertar(15);    */
       
       BB.Insertar(80);
    //   BB.Insertar(40);
    //   BB.Insertar(50);
     
      
     
    
        
       
       
        
            
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonInOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInOrdenActionPerformed
         Al.PreOrden(txtSalida);
    }//GEN-LAST:event_jButtonInOrdenActionPerformed

    private void jButtonmostrarParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmostrarParesActionPerformed
         Al.mostraraPares(txtSalida);
    }//GEN-LAST:event_jButtonmostrarParesActionPerformed

    private void jButtonExisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExisteActionPerformed
        int x = Integer.parseInt(txtAuxiliar.getText());
        if (Al.existe(x)){
            txtSalida.setText("Existe");
        }else txtSalida.setText("No Existe");
    }//GEN-LAST:event_jButtonExisteActionPerformed

    private void txtAuxiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuxiliarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuxiliarActionPerformed

    private void jButtonPruebasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPruebasActionPerformed
       // int x = Integer.parseInt(txtAuxiliar.getText());
       // txtSalida.setText(Integer.toString(Al.sumaElem()));  
     
           if (Al.sonIguales(BB)){
            txtSalida.setText("Existe");
        }else txtSalida.setText("No Existe");
    
    }//GEN-LAST:event_jButtonPruebasActionPerformed

    private void jButtoniIgualadadArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoniIgualadadArbolActionPerformed
        if (Al.subArbol(BB)){
           txtSalida.setText("verdadero");
        }else  txtSalida.setText("falso");
    
    }//GEN-LAST:event_jButtoniIgualadadArbolActionPerformed

    private void jButtonSumaElementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumaElementosActionPerformed
        txtSalida.setText(Integer.toString(Al.SumaElem()));
    }//GEN-LAST:event_jButtonSumaElementosActionPerformed

    private void parcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parcialActionPerformed
      txtSalida.setText(Al.BuscarDirElemxd(12));
    }//GEN-LAST:event_parcialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioMVias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioMVias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioMVias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioMVias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioMVias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExiste;
    private javax.swing.JButton jButtonInOrden;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonPruebas;
    private javax.swing.JButton jButtonSumaElementos;
    private javax.swing.JButton jButtoniIgualadadArbol;
    private javax.swing.JButton jButtonmostrarPares;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton parcial;
    private javax.swing.JTextField txtAuxiliar;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextArea txtSalida;
    // End of variables declaration//GEN-END:variables
}
