
package PackegeArbolBinarioForm;

public class FormMain extends javax.swing.JFrame {
    ArbolBinarioF Al;
    ArbolBinarioF BB;
    public FormMain() {
        initComponents();
        Al = new ArbolBinarioF();
        BB = new ArbolBinarioF();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TxtSalida = new javax.swing.JTextArea();
        TxtEntrada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ButtonInsertar = new javax.swing.JButton();
        ButtonInOrden = new javax.swing.JButton();
        ButtonPreOrden = new javax.swing.JButton();
        ButtonPostOrden = new javax.swing.JButton();
        ButtonCantidad = new javax.swing.JButton();
        ButtonSumaElem = new javax.swing.JButton();
        ButtonSumaPares = new javax.swing.JButton();
        ButtonMostrarPadres = new javax.swing.JButton();
        jButtonAltura = new javax.swing.JButton();
        jButtonPruebas = new javax.swing.JButton();
        jButtonDevolverAbuelo = new javax.swing.JButton();
        jButtonClean = new javax.swing.JButton();
        TxtAuxiliar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonDevolverPAdre = new javax.swing.JButton();
        jButtonIgualdadArbol = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtSalida2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonVerficarSubArbol = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtNivel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonMostarHojas = new javax.swing.JButton();
        jButtonSobrinos = new javax.swing.JButton();
        jButtonTiodeX = new javax.swing.JButton();
        jButtonPrimoX = new javax.swing.JButton();
        jButtonPeinadoP1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtSalida.setColumns(20);
        TxtSalida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TxtSalida.setRows(5);
        jScrollPane1.setViewportView(TxtSalida);

        TxtEntrada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TxtEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEntradaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("SALIDA DE DATOS");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("AUXILIAR");

        ButtonInsertar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonInsertar.setText("INSERTAR");
        ButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInsertarActionPerformed(evt);
            }
        });

        ButtonInOrden.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonInOrden.setText("IN ORDEN");
        ButtonInOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInOrdenActionPerformed(evt);
            }
        });

        ButtonPreOrden.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonPreOrden.setText("PRE ORDEN");
        ButtonPreOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPreOrdenActionPerformed(evt);
            }
        });

        ButtonPostOrden.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonPostOrden.setText("POST ORDEN");
        ButtonPostOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPostOrdenActionPerformed(evt);
            }
        });

        ButtonCantidad.setText("Cantidad");
        ButtonCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCantidadActionPerformed(evt);
            }
        });

        ButtonSumaElem.setText("Suma Elementos");
        ButtonSumaElem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSumaElemActionPerformed(evt);
            }
        });

        ButtonSumaPares.setText("Suma Pares");
        ButtonSumaPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSumaParesActionPerformed(evt);
            }
        });

        ButtonMostrarPadres.setText("Mostrar Padres");
        ButtonMostrarPadres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMostrarPadresActionPerformed(evt);
            }
        });

        jButtonAltura.setText("Altura");
        jButtonAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlturaActionPerformed(evt);
            }
        });

        jButtonPruebas.setText("Pruebas de Metodos");
        jButtonPruebas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPruebasActionPerformed(evt);
            }
        });

        jButtonDevolverAbuelo.setText("Devolver Abuelo");
        jButtonDevolverAbuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevolverAbueloActionPerformed(evt);
            }
        });

        jButtonClean.setText("LIMPIAR");
        jButtonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleanActionPerformed(evt);
            }
        });

        TxtAuxiliar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TxtAuxiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAuxiliarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("ENTRADA DE DATOS");

        jButtonDevolverPAdre.setText("Devolver Padre");
        jButtonDevolverPAdre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevolverPAdreActionPerformed(evt);
            }
        });

        jButtonIgualdadArbol.setText("Igualdad de Arbol");
        jButtonIgualdadArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualdadArbolActionPerformed(evt);
            }
        });

        TxtSalida2.setColumns(20);
        TxtSalida2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TxtSalida2.setRows(5);
        jScrollPane2.setViewportView(TxtSalida2);

        jLabel1.setText("Arbol A");

        jLabel5.setText("Arbol B");

        jButtonVerficarSubArbol.setText("Verificar Sub Arbol");
        jButtonVerficarSubArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerficarSubArbolActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar Elemento");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jLabel6.setText("Metodos Oscar");

        jButton1.setText("Suma Elementos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Nivel");

        jButton2.setText("Mostra >= al nivel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Mostar Hojas de X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonMostarHojas.setText("xdxd");

        jButtonSobrinos.setText("Sobrios de X");
        jButtonSobrinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobrinosActionPerformed(evt);
            }
        });

        jButtonTiodeX.setText("Tio de X");
        jButtonTiodeX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTiodeXActionPerformed(evt);
            }
        });

        jButtonPrimoX.setText("primo de X");
        jButtonPrimoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimoXActionPerformed(evt);
            }
        });

        jButtonPeinadoP1.setText("Peinado P1");
        jButtonPeinadoP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPeinadoP1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonInOrden)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonPreOrden)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonPostOrden))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(ButtonCantidad)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ButtonSumaElem)
                                    .addGap(18, 18, 18)
                                    .addComponent(ButtonSumaPares)
                                    .addGap(27, 27, 27)
                                    .addComponent(ButtonMostrarPadres))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButtonEliminar)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButtonPrimoX)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonPeinadoP1))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonAltura)
                                                .addGap(26, 26, 26)
                                                .addComponent(jButtonDevolverAbuelo)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonDevolverPAdre))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonIgualdadArbol)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonVerficarSubArbol))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButtonSobrinos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonTiodeX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(42, 42, 42))
                            .addComponent(TxtAuxiliar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPruebas)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonInsertar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNivel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonClean)
                                .addGap(198, 198, 198)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(jButtonMostarHojas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(ButtonInsertar)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addComponent(jLabel6))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TxtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtAuxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2)))
                        .addGap(1, 1, 1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClean)
                    .addComponent(jButton3)
                    .addComponent(jButtonMostarHojas))
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPruebas)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonInOrden)
                    .addComponent(ButtonPreOrden)
                    .addComponent(ButtonPostOrden))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCantidad)
                    .addComponent(ButtonSumaElem)
                    .addComponent(ButtonSumaPares)
                    .addComponent(ButtonMostrarPadres))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAltura)
                    .addComponent(jButtonDevolverAbuelo)
                    .addComponent(jButtonDevolverPAdre)
                    .addComponent(jButtonSobrinos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIgualdadArbol)
                    .addComponent(jButtonVerficarSubArbol)
                    .addComponent(jButtonTiodeX))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminar)
                    .addComponent(jButtonPrimoX)
                    .addComponent(jButtonPeinadoP1))
                .addContainerGap(280, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    //Metodo INSERTAR
    private void ButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInsertarActionPerformed
      //  Al.Insertar(Integer.parseInt(TxtEntrada.getText()));
    
        Al.Insertar(50);  
        Al.Insertar(10);
        Al.Insertar(60);
        Al.Insertar(15);
        Al.Insertar(55); 
//         Al.Insertar(6);
//          Al.Insertar(6);
//           Al.Insertar(6);
        
//        Al.Insertar(18);
//        Al.Insertar(24);
//        Al.Insertar(1);
//        Al.Insertar(4);
//        Al.Insertar(7);
//        Al.Insertar(12);
//        Al.Insertar(17);
//   /*
        
//        if (TxtEntrada.getText() != "")
//            Al.Insertar(Integer.parseInt(TxtEntrada.getText()));*/
//        
//        BB.Insertar(15);  
//        BB.Insertar(6);
//        BB.Insertar(20);
//        BB.Insertar(3);
//        BB.Insertar(9); 
//       
//      
//  
        
    }//GEN-LAST:event_ButtonInsertarActionPerformed

    private void ButtonInOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInOrdenActionPerformed
         Al.inOrden(TxtSalida); 
         BB.inOrden(TxtSalida2);
    }//GEN-LAST:event_ButtonInOrdenActionPerformed

    private void ButtonPreOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPreOrdenActionPerformed
        Al.preOrden(TxtSalida);
    }//GEN-LAST:event_ButtonPreOrdenActionPerformed

    private void ButtonPostOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPostOrdenActionPerformed
        Al.postOrden(TxtSalida);
        
    }//GEN-LAST:event_ButtonPostOrdenActionPerformed

    private void ButtonCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCantidadActionPerformed
        TxtSalida.setText(Integer.toString(Al.cantidad()));
    }//GEN-LAST:event_ButtonCantidadActionPerformed

    private void ButtonSumaElemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSumaElemActionPerformed
        TxtSalida.setText(Integer.toString(Al.sumaElementos()));
    }//GEN-LAST:event_ButtonSumaElemActionPerformed

    private void ButtonSumaParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSumaParesActionPerformed
         TxtSalida.setText(Integer.toString(Al.SumaPares()));
    }//GEN-LAST:event_ButtonSumaParesActionPerformed

    private void ButtonMostrarPadresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMostrarPadresActionPerformed
        int x = Integer.parseInt(TxtAuxiliar.getText());
        TxtSalida.setText(Integer.toString(Al.mostrarPadresX(x)));
    }//GEN-LAST:event_ButtonMostrarPadresActionPerformed

    private void jButtonAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlturaActionPerformed
        TxtSalida.setText(Integer.toString(Al.altura()));
    }//GEN-LAST:event_jButtonAlturaActionPerformed

    private void jButtonPruebasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPruebasActionPerformed
        //int x = Integer.parseInt(txtNivel.getText());
       // TxtSalida.setText(Integer.toString(Al.alturaMayor()));
    }//GEN-LAST:event_jButtonPruebasActionPerformed

    private void jButtonDevolverAbueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevolverAbueloActionPerformed
        TxtSalida.setText(Integer.toString(Al.devolverAbuelo(
                Integer.parseInt(TxtAuxiliar.getText()))));
    }//GEN-LAST:event_jButtonDevolverAbueloActionPerformed

    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed
        TxtSalida.setText("");
    }//GEN-LAST:event_jButtonCleanActionPerformed

    private void TxtEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEntradaActionPerformed

    private void TxtAuxiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAuxiliarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAuxiliarActionPerformed

    private void jButtonDevolverPAdreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevolverPAdreActionPerformed
         TxtSalida.setText(Integer.toString(Al.devolverPadre(
                Integer.parseInt(TxtAuxiliar.getText()))));
    }//GEN-LAST:event_jButtonDevolverPAdreActionPerformed

    private void jButtonIgualdadArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualdadArbolActionPerformed
 
        if (Al.igualdaArboles2(BB))
            TxtSalida.setText("Son iguales");
        else TxtSalida.setText("No son iguales");
    }//GEN-LAST:event_jButtonIgualdadArbolActionPerformed

    private void jButtonVerficarSubArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerficarSubArbolActionPerformed
        if (Al.verificarSubArbol(BB))
            TxtSalida.setText("Es un sub arbol");
        else TxtSalida.setText("No es sub arbol");
    }//GEN-LAST:event_jButtonVerficarSubArbolActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        Al.eliminar(Integer.parseInt(TxtAuxiliar.getText()));
        Al.inOrden(TxtSalida2);
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int nivel = Integer.parseInt(txtNivel.getText());
        TxtSalida.setText(Integer.toString(Al.sumaElemLevel(nivel)));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int nivel = Integer.parseInt(txtNivel.getText());
        Al.mostrarElemNivel(nivel, TxtSalida);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int X = Integer.parseInt(txtNivel.getText());
        Al.mostrarHojasX(X, TxtSalida);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonSobrinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobrinosActionPerformed
        int X = Integer.parseInt(TxtAuxiliar.getText());
        Al.mostrarSobrinosX(X, TxtSalida);
    }//GEN-LAST:event_jButtonSobrinosActionPerformed

    private void jButtonTiodeXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTiodeXActionPerformed
        int X = Integer.parseInt(TxtAuxiliar.getText());
        Al.mostrarTioX(X, TxtSalida);
    }//GEN-LAST:event_jButtonTiodeXActionPerformed

    private void jButtonPrimoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimoXActionPerformed
        Al.mostrarPrimosX(4, TxtSalida);
    }//GEN-LAST:event_jButtonPrimoXActionPerformed

    private void jButtonPeinadoP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeinadoP1ActionPerformed
        Al.Parcial1(TxtSalida);
    }//GEN-LAST:event_jButtonPeinadoP1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCantidad;
    private javax.swing.JButton ButtonInOrden;
    private javax.swing.JButton ButtonInsertar;
    private javax.swing.JButton ButtonMostrarPadres;
    private javax.swing.JButton ButtonPostOrden;
    private javax.swing.JButton ButtonPreOrden;
    private javax.swing.JButton ButtonSumaElem;
    private javax.swing.JButton ButtonSumaPares;
    private javax.swing.JTextField TxtAuxiliar;
    private javax.swing.JTextField TxtEntrada;
    private javax.swing.JTextArea TxtSalida;
    private javax.swing.JTextArea TxtSalida2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAltura;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JButton jButtonDevolverAbuelo;
    private javax.swing.JButton jButtonDevolverPAdre;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonIgualdadArbol;
    private javax.swing.JButton jButtonMostarHojas;
    private javax.swing.JButton jButtonPeinadoP1;
    private javax.swing.JButton jButtonPrimoX;
    private javax.swing.JButton jButtonPruebas;
    private javax.swing.JButton jButtonSobrinos;
    private javax.swing.JButton jButtonTiodeX;
    private javax.swing.JButton jButtonVerficarSubArbol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtNivel;
    // End of variables declaration//GEN-END:variables
}
